name: Regression Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches: 
      - main
      - master
  schedule:
    - cron: '11 16 * * *' # Runs every day at 3pm EST
  workflow_dispatch:

jobs:
  regression-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright Chromium Browser
      - name: Install Playwright chrome
        run: npx playwright install --with-deps chromium

      # Configure environment variables from secrets
      - name: Configure environment variables from secrets
        run: |
          echo "PRACTICE_USERNAME=${{ secrets.PRACTICE_USERNAME }}" >> .env
          echo "PRACTICE_PASSWORD=${{ secrets.PRACTICE_PASSWORD }}" >> .env

      # Run Playwright tests
      - name: Run Playwright tests
        run: npm run tests:headless



      # Upload Playwright HTML report
      - name: Upload playwright HTML report
        if: always() # Ensure this step runs even if the tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
